### PR TITLE
get ready for precompilation

### PR DESCRIPTION
**Pull request by SimonDanisch**
By the way I'm using this package now to render text =)
I also added lines, but I still need some more time to clean everything up.
But here's a little teaser: https://drive.google.com/folderview?id=0B9vNkD-OdlWNV3dCUWJyeTk3aDA&usp=sharing

### CODE REVIEW

**Comment by yurivish** [comment]
Sweet! Which approach to rendering lines are you using? I just implemented a mitered polyline renderer using Swift and Metal (on iOS) and it still has some trouble with edge cases but is looking pretty good.

Also, do you think precompiling such a tiny package is worth it? My impression was that it's done mostly for speed and there wouldn't be much of a difference with a package this size.

**Comment by SimonDanisch** [comment]
Pretty much the mapbox one... in principle. I create the quads in a geometry shader though.
Ugh metal... I really hope apple shoots itself in the knee with that! 
But metal should still be similar enough to share algorithms. I'm in the same situation: looks nice, but a lot of edge cases are not covered.

Concerning precompilation: it's more a question of consistency then load times. Also sometimes julia complains when this statement is missing. Not sure if it was a bug though ;)

**Comment by yurivish** [comment]
Yeah, in the lines case Metal is just used to draw triangle strips, then do some antialiasing in a shader. But the practical upshot is that I'm making a new version of Silk (http://weavesilk.com) for iOS. :)

Hmm... Is it the case that a package can be precompiled only if all of its dependencies can be precompiled? If so, it's weird that it only complains sometimes.

**Comment by SimonDanisch** [comment]
> Is it the case that a package can be precompiled only if all of its dependencies can be precompiled?

Yeah I thought so, untill I found out that I've missed this statement in some packages.

**Pull request merged**
